file_app/config/routes.rb
Rails.application.routes.draw do

  resources :folder do
    member do
      post 'content'
    end
  end
  post 'folder/content' => 'folder#content'
  post 'folder/show_file' => 'folder#show_file'
  post 'folder/create_file' => 'folder#create_file'
  post 'folder/download_file' => 'folder#download_file'
  resources :uploader
  post "uploader/create"

end

file_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


  protect_from_forgery with: :exception
end

file_app/app/controllers/folder_controller.rb
class FolderController < ApplicationController

  def index
    @folders=directory_hash("#{Rails.root}/public", name=nil);
  end


  def show_file
    @myfile = File.read(params[:paths])

    render :text => @myfile
  end

  def create_file
    path = params[:paths]
    content = params[:content]

    @myfile=File.open(path, "w+") do |f|
      f.write(content)
    end
    render :text => @myfile
  end

  def content
    @folders=directory_hash(params[:paths], name=nil);
   render :partial => "list"

  end

  def download_file
    file_path= params[:download][:filepath]
    send_file Rails.root.join(file_path)
  end


  private

  def directory_hash(path, name=nil)
    data = {:data => (name || path)}
    data[:children] = children = []
    Dir.foreach(path) do |entry|
      next if (entry == '..' || entry == '.')
      full_path = File.join(path, entry)
      if File.directory?(full_path)
        children << directory_hash(full_path, entry)
      else
        children << entry
      end
    end
    return data
  end
end

file_app/app/controllers/uploader_controller.rb
class UploaderController < ApplicationController
  def new

  end
  def create
    name = params[:uploader][:file].original_filename
    path = Rails.root.join('public','files', name)
    File.open(path, "wb") { |f| f.write(params[:uploader][:file].read) }
    flash[:notice] = "File uploaded"
    redirect_to folder_index_path
  end
end

file_app/app/helpers/application_helper.rb
module ApplicationHelper
end

file_app/app/helpers/folder_helper.rb
module FolderHelper
end

file_app/app/helpers/uploader_helper.rb
module UploaderHelper
end

file_app/app/views/folder/_list.html.erb
<ul>
    <% @folders[:children].each do |item| %>
    <% if item.is_a?(Hash) %>

    <li class="open-folder" data-path="<%=@folders[:data]+'/'+item[:data]%>">
        <i class="fa fa-folder" aria-hidden="true"></i>
        <%= item[:data] %>
    </li>
    <% else %>
    <li class="open-file" data-path="<%=@folders[:data]+'/'+item%>">
        <i class="fa fa-file-text-o" aria-hidden="true"></i>
        <%= item %>
      <%= form_for :download, url: folder_download_file_path do |f|%>
        <%=f.hidden_field :filepath, value: @folders[:data]+'/'+item %>
        <%=f.submit class: "fa fa-download download-file", value:'Download'%>
      <%end%>
    </li>
    <% end %>
    <% end %>
</ul>

file_app/app/views/folder/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">

      <span class="folder-path"><%= @folders[:data] %></span>
      <input type="text" class="file-name" />
      <%= render partial: 'list', object: @folders %>
    </div>
    <div class="col-md-6">
      <a class="js-create" href="javascript:void(0);">
        Create File
      </a>
      <a class="js-save" href="javascript:void(0);">
        Save File
      </a>
      <textarea class="file-area" ></textarea>

    </div>
  </div>
  <div>
    <% flash.each do |key, msg| %>
        <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}" %>
    <% end %>
    <%= form_tag '/uploader/create', { :multipart => true } do %>
        <p>
          <%= file_field_tag 'uploader[file]' %>
        </p>
        <p>
          <%= submit_tag "Upload" %>
        </p>
    <% end %>
  </div>
</div>

file_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

file_app/app/views/uploader/new.html.erb
<% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}" %>
<% end %>
<%= form_tag '/uploader/create', { :multipart => true } do %>
    <p>
      <%= file_field_tag 'uploader[file]' %>
    </p>
    <p>
      <%= submit_tag "Upload" %>
    </p>
<% end %>